<?php

namespace Database\Seeders;

use App\Models\Upazila;
use Illuminate\Database\Seeder;

class UpazilaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $UpazilaList = [
            ['id' => '1', 'district_id' => '34', 'name' => 'Amtali', 'bn_name' => 'আমতলী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '2', 'district_id' => '34', 'name' => 'Bamna ', 'bn_name' => 'বামনা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '3', 'district_id' => '34', 'name' => 'Barguna Sadar ', 'bn_name' => 'বরগুনা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '4', 'district_id' => '34', 'name' => 'Betagi ', 'bn_name' => 'বেতাগি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '5', 'district_id' => '34', 'name' => 'Patharghata ', 'bn_name' => 'পাথরঘাটা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '6', 'district_id' => '34', 'name' => 'Taltali ', 'bn_name' => 'তালতলী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '7', 'district_id' => '35', 'name' => 'Muladi ', 'bn_name' => 'মুলাদি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '8', 'district_id' => '35', 'name' => 'Babuganj ', 'bn_name' => 'বাবুগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '9', 'district_id' => '35', 'name' => 'Agailjhara ', 'bn_name' => 'আগাইলঝরা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '10', 'district_id' => '35', 'name' => 'Barisal Sadar ', 'bn_name' => 'বরিশাল সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '11', 'district_id' => '35', 'name' => 'Bakerganj ', 'bn_name' => 'বাকেরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '12', 'district_id' => '35', 'name' => 'Banaripara ', 'bn_name' => 'বানাড়িপারা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '13', 'district_id' => '35', 'name' => 'Gaurnadi ', 'bn_name' => 'গৌরনদী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '14', 'district_id' => '35', 'name' => 'Hizla ', 'bn_name' => 'হিজলা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '15', 'district_id' => '35', 'name' => 'Mehendiganj ', 'bn_name' => 'মেহেদিগঞ্জ ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '16', 'district_id' => '35', 'name' => 'Wazirpur ', 'bn_name' => 'ওয়াজিরপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '17', 'district_id' => '36', 'name' => 'Bhola Sadar ', 'bn_name' => 'ভোলা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '18', 'district_id' => '36', 'name' => 'Burhanuddin ', 'bn_name' => 'বুরহানউদ্দিন', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '19', 'district_id' => '36', 'name' => 'Char Fasson ', 'bn_name' => 'চর ফ্যাশন', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '20', 'district_id' => '36', 'name' => 'Daulatkhan ', 'bn_name' => 'দৌলতখান', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '21', 'district_id' => '36', 'name' => 'Lalmohan ', 'bn_name' => 'লালমোহন', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '22', 'district_id' => '36', 'name' => 'Manpura ', 'bn_name' => 'মনপুরা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '23', 'district_id' => '36', 'name' => 'Tazumuddin ', 'bn_name' => 'তাজুমুদ্দিন', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '24', 'district_id' => '37', 'name' => 'Jhalokati Sadar ', 'bn_name' => 'ঝালকাঠি সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '25', 'district_id' => '37', 'name' => 'Kathalia ', 'bn_name' => 'কাঁঠালিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '26', 'district_id' => '37', 'name' => 'Nalchity ', 'bn_name' => 'নালচিতি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '27', 'district_id' => '37', 'name' => 'Rajapur ', 'bn_name' => 'রাজাপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '28', 'district_id' => '38', 'name' => 'Bauphal ', 'bn_name' => 'বাউফল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '29', 'district_id' => '38', 'name' => 'Dashmina ', 'bn_name' => 'দশমিনা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '30', 'district_id' => '38', 'name' => 'Galachipa ', 'bn_name' => 'গলাচিপা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '31', 'district_id' => '38', 'name' => 'Kalapara ', 'bn_name' => 'কালাপারা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '32', 'district_id' => '38', 'name' => 'Mirzaganj ', 'bn_name' => 'মির্জাগঞ্জ ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '33', 'district_id' => '38', 'name' => 'Patuakhali Sadar ', 'bn_name' => 'পটুয়াখালী সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '34', 'district_id' => '38', 'name' => 'Dumki ', 'bn_name' => 'ডুমকি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '35', 'district_id' => '38', 'name' => 'Rangabali ', 'bn_name' => 'রাঙ্গাবালি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '36', 'district_id' => '39', 'name' => 'Bhandaria', 'bn_name' => 'ভ্যান্ডারিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '37', 'district_id' => '39', 'name' => 'Kaukhali', 'bn_name' => 'কাউখালি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '38', 'district_id' => '39', 'name' => 'Mathbaria', 'bn_name' => 'মাঠবাড়িয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '39', 'district_id' => '39', 'name' => 'Nazirpur', 'bn_name' => 'নাজিরপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '40', 'district_id' => '39', 'name' => 'Nesarabad', 'bn_name' => 'নেসারাবাদ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '41', 'district_id' => '39', 'name' => 'Pirojpur Sadar', 'bn_name' => 'পিরোজপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '42', 'district_id' => '39', 'name' => 'Zianagar', 'bn_name' => 'জিয়ানগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '43', 'district_id' => '40', 'name' => 'Bandarban Sadar', 'bn_name' => 'বান্দরবন সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '44', 'district_id' => '40', 'name' => 'Thanchi', 'bn_name' => 'থানচি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '45', 'district_id' => '40', 'name' => 'Lama', 'bn_name' => 'লামা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '46', 'district_id' => '40', 'name' => 'Naikhongchhari', 'bn_name' => 'নাইখংছড়ি ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '47', 'district_id' => '40', 'name' => 'Ali kadam', 'bn_name' => 'আলী কদম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '48', 'district_id' => '40', 'name' => 'Rowangchhari', 'bn_name' => 'রউয়াংছড়ি ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '49', 'district_id' => '40', 'name' => 'Ruma', 'bn_name' => 'রুমা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '50', 'district_id' => '41', 'name' => 'Brahmanbaria Sadar ', 'bn_name' => 'ব্রাহ্মণবাড়িয়া সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '51', 'district_id' => '41', 'name' => 'Ashuganj ', 'bn_name' => 'আশুগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '52', 'district_id' => '41', 'name' => 'Nasirnagar ', 'bn_name' => 'নাসির নগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '53', 'district_id' => '41', 'name' => 'Nabinagar ', 'bn_name' => 'নবীনগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '54', 'district_id' => '41', 'name' => 'Sarail ', 'bn_name' => 'সরাইল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '55', 'district_id' => '41', 'name' => 'Shahbazpur Town', 'bn_name' => 'শাহবাজপুর টাউন', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '56', 'district_id' => '41', 'name' => 'Kasba ', 'bn_name' => 'কসবা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '57', 'district_id' => '41', 'name' => 'Akhaura ', 'bn_name' => 'আখাউরা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '58', 'district_id' => '41', 'name' => 'Bancharampur ', 'bn_name' => 'বাঞ্ছারামপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '59', 'district_id' => '41', 'name' => 'Bijoynagar ', 'bn_name' => 'বিজয় নগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '60', 'district_id' => '42', 'name' => 'Chandpur Sadar', 'bn_name' => 'চাঁদপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '61', 'district_id' => '42', 'name' => 'Faridganj', 'bn_name' => 'ফরিদগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '62', 'district_id' => '42', 'name' => 'Haimchar', 'bn_name' => 'হাইমচর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '63', 'district_id' => '42', 'name' => 'Haziganj', 'bn_name' => 'হাজীগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '64', 'district_id' => '42', 'name' => 'Kachua', 'bn_name' => 'কচুয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '65', 'district_id' => '42', 'name' => 'Matlab Uttar', 'bn_name' => 'মতলব উত্তর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '66', 'district_id' => '42', 'name' => 'Matlab Dakkhin', 'bn_name' => 'মতলব দক্ষিণ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '67', 'district_id' => '42', 'name' => 'Shahrasti', 'bn_name' => 'শাহরাস্তি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '68', 'district_id' => '43', 'name' => 'Anwara ', 'bn_name' => 'আনোয়ারা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '69', 'district_id' => '43', 'name' => 'Banshkhali ', 'bn_name' => 'বাশখালি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '70', 'district_id' => '43', 'name' => 'Boalkhali ', 'bn_name' => 'বোয়ালখালি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '71', 'district_id' => '43', 'name' => 'Chandanaish ', 'bn_name' => 'চন্দনাইশ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '72', 'district_id' => '43', 'name' => 'Fatikchhari ', 'bn_name' => 'ফটিকছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '73', 'district_id' => '43', 'name' => 'Hathazari ', 'bn_name' => 'হাঠহাজারী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '74', 'district_id' => '43', 'name' => 'Lohagara ', 'bn_name' => 'লোহাগারা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '75', 'district_id' => '43', 'name' => 'Mirsharai ', 'bn_name' => 'মিরসরাই', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '76', 'district_id' => '43', 'name' => 'Patiya ', 'bn_name' => 'পটিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '77', 'district_id' => '43', 'name' => 'Rangunia ', 'bn_name' => 'রাঙ্গুনিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '78', 'district_id' => '43', 'name' => 'Raozan ', 'bn_name' => 'রাউজান', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '79', 'district_id' => '43', 'name' => 'Sandwip ', 'bn_name' => 'সন্দ্বীপ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '80', 'district_id' => '43', 'name' => 'Satkania ', 'bn_name' => 'সাতকানিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '81', 'district_id' => '43', 'name' => 'Sitakunda ', 'bn_name' => 'সীতাকুণ্ড', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '82', 'district_id' => '44', 'name' => 'Barura ', 'bn_name' => 'বড়ুরা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '83', 'district_id' => '44', 'name' => 'Brahmanpara ', 'bn_name' => 'ব্রাহ্মণপাড়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '84', 'district_id' => '44', 'name' => 'Burichong ', 'bn_name' => 'বুড়িচং', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '85', 'district_id' => '44', 'name' => 'Chandina ', 'bn_name' => 'চান্দিনা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '86', 'district_id' => '44', 'name' => 'Chauddagram ', 'bn_name' => 'চৌদ্দগ্রাম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '87', 'district_id' => '44', 'name' => 'Daudkandi ', 'bn_name' => 'দাউদকান্দি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '88', 'district_id' => '44', 'name' => 'Debidwar ', 'bn_name' => 'দেবীদ্বার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '89', 'district_id' => '44', 'name' => 'Homna ', 'bn_name' => 'হোমনা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '90', 'district_id' => '44', 'name' => 'Comilla Sadar ', 'bn_name' => 'কুমিল্লা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '91', 'district_id' => '44', 'name' => 'Laksam ', 'bn_name' => 'লাকসাম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '92', 'district_id' => '44', 'name' => 'Monohorgonj ', 'bn_name' => 'মনোহরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '93', 'district_id' => '44', 'name' => 'Meghna ', 'bn_name' => 'মেঘনা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '94', 'district_id' => '44', 'name' => 'Muradnagar ', 'bn_name' => 'মুরাদনগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '95', 'district_id' => '44', 'name' => 'Nangalkot ', 'bn_name' => 'নাঙ্গালকোট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '96', 'district_id' => '44', 'name' => 'Comilla Sadar South ', 'bn_name' => 'কুমিল্লা সদর দক্ষিণ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '97', 'district_id' => '44', 'name' => 'Titas ', 'bn_name' => 'তিতাস', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '98', 'district_id' => '45', 'name' => 'Chakaria ', 'bn_name' => 'চকরিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '99', 'district_id' => '45', 'name' => 'Chakaria ', 'bn_name' => 'চকরিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '100', 'district_id' => '45', 'name' => "Cox's Bazar Sadar ", 'bn_name' => 'কক্স বাজার সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '101', 'district_id' => '45', 'name' => 'Kutubdia ', 'bn_name' => 'কুতুবদিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '102', 'district_id' => '45', 'name' => 'Maheshkhali ', 'bn_name' => 'মহেশখালী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '103', 'district_id' => '45', 'name' => 'Ramu ', 'bn_name' => 'রামু', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '104', 'district_id' => '45', 'name' => 'Teknaf ', 'bn_name' => 'টেকনাফ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '105', 'district_id' => '45', 'name' => 'Ukhia ', 'bn_name' => 'উখিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '106', 'district_id' => '45', 'name' => 'Pekua ', 'bn_name' => 'পেকুয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '107', 'district_id' => '46', 'name' => 'Feni Sadar', 'bn_name' => 'ফেনী সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '108', 'district_id' => '46', 'name' => 'Chagalnaiya', 'bn_name' => 'ছাগল নাইয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '109', 'district_id' => '46', 'name' => 'Daganbhyan', 'bn_name' => 'দাগানভিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '110', 'district_id' => '46', 'name' => 'Parshuram', 'bn_name' => 'পরশুরাম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '111', 'district_id' => '46', 'name' => 'Fhulgazi', 'bn_name' => 'ফুলগাজি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '112', 'district_id' => '46', 'name' => 'Sonagazi', 'bn_name' => 'সোনাগাজি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '113', 'district_id' => '47', 'name' => 'Dighinala ', 'bn_name' => 'দিঘিনালা ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '114', 'district_id' => '47', 'name' => 'Khagrachhari ', 'bn_name' => 'খাগড়াছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '115', 'district_id' => '47', 'name' => 'Lakshmichhari ', 'bn_name' => 'লক্ষ্মীছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '116', 'district_id' => '47', 'name' => 'Mahalchhari ', 'bn_name' => 'মহলছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '117', 'district_id' => '47', 'name' => 'Manikchhari ', 'bn_name' => 'মানিকছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '118', 'district_id' => '47', 'name' => 'Matiranga ', 'bn_name' => 'মাটিরাঙ্গা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '119', 'district_id' => '47', 'name' => 'Panchhari ', 'bn_name' => 'পানছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '120', 'district_id' => '47', 'name' => 'Ramgarh ', 'bn_name' => 'রামগড়', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '121', 'district_id' => '48', 'name' => 'Lakshmipur Sadar ', 'bn_name' => 'লক্ষ্মীপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '122', 'district_id' => '48', 'name' => 'Raipur ', 'bn_name' => 'রায়পুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '123', 'district_id' => '48', 'name' => 'Ramganj ', 'bn_name' => 'রামগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '124', 'district_id' => '48', 'name' => 'Ramgati ', 'bn_name' => 'রামগতি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '125', 'district_id' => '48', 'name' => 'Komol Nagar ', 'bn_name' => 'কমল নগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '126', 'district_id' => '49', 'name' => 'Noakhali Sadar ', 'bn_name' => 'নোয়াখালী সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '127', 'district_id' => '49', 'name' => 'Begumganj ', 'bn_name' => 'বেগমগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '128', 'district_id' => '49', 'name' => 'Chatkhil ', 'bn_name' => 'চাটখিল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '129', 'district_id' => '49', 'name' => 'Companyganj ', 'bn_name' => 'কোম্পানীগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '130', 'district_id' => '49', 'name' => 'Shenbag ', 'bn_name' => 'শেনবাগ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '131', 'district_id' => '49', 'name' => 'Hatia ', 'bn_name' => 'হাতিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '132', 'district_id' => '49', 'name' => 'Kobirhat ', 'bn_name' => 'কবিরহাট ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '133', 'district_id' => '49', 'name' => 'Sonaimuri ', 'bn_name' => 'সোনাইমুরি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '134', 'district_id' => '49', 'name' => 'Suborno Char ', 'bn_name' => 'সুবর্ণ চর ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '135', 'district_id' => '50', 'name' => 'Rangamati Sadar ', 'bn_name' => 'রাঙ্গামাটি সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '136', 'district_id' => '50', 'name' => 'Belaichhari ', 'bn_name' => 'বেলাইছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '137', 'district_id' => '50', 'name' => 'Bagaichhari ', 'bn_name' => 'বাঘাইছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '138', 'district_id' => '50', 'name' => 'Barkal ', 'bn_name' => 'বরকল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '139', 'district_id' => '50', 'name' => 'Juraichhari ', 'bn_name' => 'জুরাইছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '140', 'district_id' => '50', 'name' => 'Rajasthali ', 'bn_name' => 'রাজাস্থলি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '141', 'district_id' => '50', 'name' => 'Kaptai ', 'bn_name' => 'কাপ্তাই', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '142', 'district_id' => '50', 'name' => 'Langadu ', 'bn_name' => 'লাঙ্গাডু', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '143', 'district_id' => '50', 'name' => 'Nannerchar ', 'bn_name' => 'নান্নেরচর ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '144', 'district_id' => '50', 'name' => 'Kaukhali ', 'bn_name' => 'কাউখালি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '150', 'district_id' => '2', 'name' => 'Faridpur Sadar ', 'bn_name' => 'ফরিদপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '151', 'district_id' => '2', 'name' => 'Boalmari ', 'bn_name' => 'বোয়ালমারী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '152', 'district_id' => '2', 'name' => 'Alfadanga ', 'bn_name' => 'আলফাডাঙ্গা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '153', 'district_id' => '2', 'name' => 'Madhukhali ', 'bn_name' => 'মধুখালি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '154', 'district_id' => '2', 'name' => 'Bhanga ', 'bn_name' => 'ভাঙ্গা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '155', 'district_id' => '2', 'name' => 'Nagarkanda ', 'bn_name' => 'নগরকান্ড', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '156', 'district_id' => '2', 'name' => 'Charbhadrasan ', 'bn_name' => 'চরভদ্রাসন ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '157', 'district_id' => '2', 'name' => 'Sadarpur ', 'bn_name' => 'সদরপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '158', 'district_id' => '2', 'name' => 'Shaltha ', 'bn_name' => 'শালথা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '159', 'district_id' => '3', 'name' => 'Gazipur Sadar-Joydebpur', 'bn_name' => 'গাজীপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '160', 'district_id' => '3', 'name' => 'Kaliakior', 'bn_name' => 'কালিয়াকৈর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '161', 'district_id' => '3', 'name' => 'Kapasia', 'bn_name' => 'কাপাসিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '162', 'district_id' => '3', 'name' => 'Sripur', 'bn_name' => 'শ্রীপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '163', 'district_id' => '3', 'name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '164', 'district_id' => '3', 'name' => 'Tongi', 'bn_name' => 'টঙ্গি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '165', 'district_id' => '4', 'name' => 'Gopalganj Sadar ', 'bn_name' => 'গোপালগঞ্জ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '166', 'district_id' => '4', 'name' => 'Kashiani ', 'bn_name' => 'কাশিয়ানি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '167', 'district_id' => '4', 'name' => 'Kotalipara ', 'bn_name' => 'কোটালিপাড়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '168', 'district_id' => '4', 'name' => 'Muksudpur ', 'bn_name' => 'মুকসুদপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '169', 'district_id' => '4', 'name' => 'Tungipara ', 'bn_name' => 'টুঙ্গিপাড়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '170', 'district_id' => '5', 'name' => 'Dewanganj ', 'bn_name' => 'দেওয়ানগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '171', 'district_id' => '5', 'name' => 'Baksiganj ', 'bn_name' => 'বকসিগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '172', 'district_id' => '5', 'name' => 'Islampur ', 'bn_name' => 'ইসলামপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '173', 'district_id' => '5', 'name' => 'Jamalpur Sadar ', 'bn_name' => 'জামালপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '174', 'district_id' => '5', 'name' => 'Madarganj ', 'bn_name' => 'মাদারগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '175', 'district_id' => '5', 'name' => 'Melandaha ', 'bn_name' => 'মেলানদাহা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '176', 'district_id' => '5', 'name' => 'Sarishabari ', 'bn_name' => 'সরিষাবাড়ি ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '177', 'district_id' => '5', 'name' => 'Narundi Police I.C', 'bn_name' => 'নারুন্দি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '178', 'district_id' => '6', 'name' => 'Astagram ', 'bn_name' => 'অষ্টগ্রাম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '179', 'district_id' => '6', 'name' => 'Bajitpur ', 'bn_name' => 'বাজিতপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '180', 'district_id' => '6', 'name' => 'Bhairab ', 'bn_name' => 'ভৈরব', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '181', 'district_id' => '6', 'name' => 'Hossainpur ', 'bn_name' => 'হোসেনপুর ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '182', 'district_id' => '6', 'name' => 'Itna ', 'bn_name' => 'ইটনা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '183', 'district_id' => '6', 'name' => 'Karimganj ', 'bn_name' => 'করিমগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '184', 'district_id' => '6', 'name' => 'Katiadi ', 'bn_name' => 'কতিয়াদি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '185', 'district_id' => '6', 'name' => 'Kishoreganj Sadar ', 'bn_name' => 'কিশোরগঞ্জ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '186', 'district_id' => '6', 'name' => 'Kuliarchar ', 'bn_name' => 'কুলিয়ারচর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '187', 'district_id' => '6', 'name' => 'Mithamain ', 'bn_name' => 'মিঠামাইন', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '188', 'district_id' => '6', 'name' => 'Nikli ', 'bn_name' => 'নিকলি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '189', 'district_id' => '6', 'name' => 'Pakundia ', 'bn_name' => 'পাকুন্ডা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '190', 'district_id' => '6', 'name' => 'Tarail ', 'bn_name' => 'তাড়াইল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '191', 'district_id' => '7', 'name' => 'Madaripur Sadar', 'bn_name' => 'মাদারীপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '192', 'district_id' => '7', 'name' => 'Kalkini', 'bn_name' => 'কালকিনি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '193', 'district_id' => '7', 'name' => 'Rajoir', 'bn_name' => 'রাজইর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '194', 'district_id' => '7', 'name' => 'Shibchar', 'bn_name' => 'শিবচর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '195', 'district_id' => '8', 'name' => 'Manikganj Sadar ', 'bn_name' => 'মানিকগঞ্জ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '196', 'district_id' => '8', 'name' => 'Singair ', 'bn_name' => 'সিঙ্গাইর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '197', 'district_id' => '8', 'name' => 'Shibalaya ', 'bn_name' => 'শিবালয়', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '198', 'district_id' => '8', 'name' => 'Saturia ', 'bn_name' => 'সাঠুরিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '199', 'district_id' => '8', 'name' => 'Harirampur ', 'bn_name' => 'হরিরামপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '200', 'district_id' => '8', 'name' => 'Ghior ', 'bn_name' => 'ঘিওর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '201', 'district_id' => '8', 'name' => 'Daulatpur ', 'bn_name' => 'দৌলতপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '202', 'district_id' => '9', 'name' => 'Lohajang ', 'bn_name' => 'লোহাজং', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '203', 'district_id' => '9', 'name' => 'Sreenagar ', 'bn_name' => 'শ্রীনগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '204', 'district_id' => '9', 'name' => 'Munshiganj Sadar ', 'bn_name' => 'মুন্সিগঞ্জ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '205', 'district_id' => '9', 'name' => 'Sirajdikhan ', 'bn_name' => 'সিরাজদিখান', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '206', 'district_id' => '9', 'name' => 'Tongibari ', 'bn_name' => 'টঙ্গিবাড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '207', 'district_id' => '9', 'name' => 'Gazaria ', 'bn_name' => 'গজারিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '208', 'district_id' => '10', 'name' => 'Bhaluka', 'bn_name' => 'ভালুকা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '209', 'district_id' => '10', 'name' => 'Trishal', 'bn_name' => 'ত্রিশাল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '210', 'district_id' => '10', 'name' => 'Haluaghat', 'bn_name' => 'হালুয়াঘাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '211', 'district_id' => '10', 'name' => 'Muktagachha', 'bn_name' => 'মুক্তাগাছা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '212', 'district_id' => '10', 'name' => 'Dhobaura', 'bn_name' => 'ধবারুয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '213', 'district_id' => '10', 'name' => 'Fulbaria', 'bn_name' => 'ফুলবাড়িয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '214', 'district_id' => '10', 'name' => 'Gaffargaon', 'bn_name' => 'গফরগাঁও', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '215', 'district_id' => '10', 'name' => 'Gauripur', 'bn_name' => 'গৌরিপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '216', 'district_id' => '10', 'name' => 'Ishwarganj', 'bn_name' => 'ঈশ্বরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '217', 'district_id' => '10', 'name' => 'Mymensingh Sadar', 'bn_name' => 'ময়মনসিং সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '218', 'district_id' => '10', 'name' => 'Nandail', 'bn_name' => 'নন্দাইল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '219', 'district_id' => '10', 'name' => 'Phulpur', 'bn_name' => 'ফুলপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '220', 'district_id' => '11', 'name' => 'Araihazar ', 'bn_name' => 'আড়াইহাজার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '221', 'district_id' => '11', 'name' => 'Sonargaon ', 'bn_name' => 'সোনারগাঁও', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '222', 'district_id' => '11', 'name' => 'Bandar', 'bn_name' => 'বান্দার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '223', 'district_id' => '11', 'name' => 'Naryanganj Sadar ', 'bn_name' => 'নারায়ানগঞ্জ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '224', 'district_id' => '11', 'name' => 'Rupganj ', 'bn_name' => 'রূপগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '225', 'district_id' => '11', 'name' => 'Siddirgonj ', 'bn_name' => 'সিদ্ধিরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '226', 'district_id' => '12', 'name' => 'Belabo ', 'bn_name' => 'বেলাবো', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '227', 'district_id' => '12', 'name' => 'Monohardi ', 'bn_name' => 'মনোহরদি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '228', 'district_id' => '12', 'name' => 'Narsingdi Sadar ', 'bn_name' => 'নরসিংদী সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '229', 'district_id' => '12', 'name' => 'Palash ', 'bn_name' => 'পলাশ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '230', 'district_id' => '12', 'name' => 'Raipura , Narsingdi', 'bn_name' => 'রায়পুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '231', 'district_id' => '12', 'name' => 'Shibpur ', 'bn_name' => 'শিবপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '232', 'district_id' => '13', 'name' => 'Kendua Upazilla', 'bn_name' => 'কেন্দুয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '233', 'district_id' => '13', 'name' => 'Atpara Upazilla', 'bn_name' => 'আটপাড়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '234', 'district_id' => '13', 'name' => 'Barhatta Upazilla', 'bn_name' => 'বরহাট্টা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '235', 'district_id' => '13', 'name' => 'Durgapur Upazilla', 'bn_name' => 'দুর্গাপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '236', 'district_id' => '13', 'name' => 'Kalmakanda Upazilla', 'bn_name' => 'কলমাকান্দা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '237', 'district_id' => '13', 'name' => 'Madan Upazilla', 'bn_name' => 'মদন', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '238', 'district_id' => '13', 'name' => 'Mohanganj Upazilla', 'bn_name' => 'মোহনগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '239', 'district_id' => '13', 'name' => 'Netrakona-S Upazilla', 'bn_name' => 'নেত্রকোনা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '240', 'district_id' => '13', 'name' => 'Purbadhala Upazilla', 'bn_name' => 'পূর্বধলা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '241', 'district_id' => '13', 'name' => 'Khaliajuri Upazilla', 'bn_name' => 'খালিয়াজুরি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '242', 'district_id' => '14', 'name' => 'Baliakandi ', 'bn_name' => 'বালিয়াকান্দি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '243', 'district_id' => '14', 'name' => 'Goalandaghat ', 'bn_name' => 'গোয়ালন্দ ঘাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '244', 'district_id' => '14', 'name' => 'Pangsha ', 'bn_name' => 'পাংশা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '245', 'district_id' => '14', 'name' => 'Kalukhali ', 'bn_name' => 'কালুখালি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '246', 'district_id' => '14', 'name' => 'Rajbari Sadar ', 'bn_name' => 'রাজবাড়ি সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '247', 'district_id' => '15', 'name' => 'Shariatpur Sadar -Palong', 'bn_name' => 'শরীয়তপুর সদর ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '248', 'district_id' => '15', 'name' => 'Damudya ', 'bn_name' => 'দামুদিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '249', 'district_id' => '15', 'name' => 'Naria ', 'bn_name' => 'নড়িয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '250', 'district_id' => '15', 'name' => 'Jajira ', 'bn_name' => 'জাজিরা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '251', 'district_id' => '15', 'name' => 'Bhedarganj ', 'bn_name' => 'ভেদারগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '252', 'district_id' => '15', 'name' => 'Gosairhat ', 'bn_name' => 'গোসাইর হাট ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '253', 'district_id' => '16', 'name' => 'Jhenaigati ', 'bn_name' => 'ঝিনাইগাতি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '254', 'district_id' => '16', 'name' => 'Nakla ', 'bn_name' => 'নাকলা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '255', 'district_id' => '16', 'name' => 'Nalitabari ', 'bn_name' => 'নালিতাবাড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '256', 'district_id' => '16', 'name' => 'Sherpur Sadar ', 'bn_name' => 'শেরপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '257', 'district_id' => '16', 'name' => 'Sreebardi ', 'bn_name' => 'শ্রীবরদি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '258', 'district_id' => '17', 'name' => 'Tangail Sadar ', 'bn_name' => 'টাঙ্গাইল সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '259', 'district_id' => '17', 'name' => 'Sakhipur ', 'bn_name' => 'সখিপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '260', 'district_id' => '17', 'name' => 'Basail ', 'bn_name' => 'বসাইল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '261', 'district_id' => '17', 'name' => 'Madhupur ', 'bn_name' => 'মধুপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '262', 'district_id' => '17', 'name' => 'Ghatail ', 'bn_name' => 'ঘাটাইল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '263', 'district_id' => '17', 'name' => 'Kalihati ', 'bn_name' => 'কালিহাতি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '264', 'district_id' => '17', 'name' => 'Nagarpur ', 'bn_name' => 'নগরপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '265', 'district_id' => '17', 'name' => 'Mirzapur ', 'bn_name' => 'মির্জাপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '266', 'district_id' => '17', 'name' => 'Gopalpur ', 'bn_name' => 'গোপালপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '267', 'district_id' => '17', 'name' => 'Delduar ', 'bn_name' => 'দেলদুয়ার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '268', 'district_id' => '17', 'name' => 'Bhuapur ', 'bn_name' => 'ভুয়াপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '269', 'district_id' => '17', 'name' => 'Dhanbari ', 'bn_name' => 'ধানবাড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '270', 'district_id' => '55', 'name' => 'Bagerhat Sadar ', 'bn_name' => 'বাগেরহাট সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '271', 'district_id' => '55', 'name' => 'Chitalmari ', 'bn_name' => 'চিতলমাড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '272', 'district_id' => '55', 'name' => 'Fakirhat ', 'bn_name' => 'ফকিরহাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '273', 'district_id' => '55', 'name' => 'Kachua ', 'bn_name' => 'কচুয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '274', 'district_id' => '55', 'name' => 'Mollahat ', 'bn_name' => 'মোল্লাহাট ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '275', 'district_id' => '55', 'name' => 'Mongla ', 'bn_name' => 'মংলা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '276', 'district_id' => '55', 'name' => 'Morrelganj ', 'bn_name' => 'মরেলগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '277', 'district_id' => '55', 'name' => 'Rampal ', 'bn_name' => 'রামপাল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '278', 'district_id' => '55', 'name' => 'Sarankhola ', 'bn_name' => 'স্মরণখোলা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '279', 'district_id' => '56', 'name' => 'Damurhuda ', 'bn_name' => 'দামুরহুদা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '280', 'district_id' => '56', 'name' => 'Chuadanga-S ', 'bn_name' => 'চুয়াডাঙ্গা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '281', 'district_id' => '56', 'name' => 'Jibannagar ', 'bn_name' => 'জীবন নগর ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '282', 'district_id' => '56', 'name' => 'Alamdanga ', 'bn_name' => 'আলমডাঙ্গা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '283', 'district_id' => '57', 'name' => 'Abhaynagar ', 'bn_name' => 'অভয়নগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '284', 'district_id' => '57', 'name' => 'Keshabpur ', 'bn_name' => 'কেশবপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '285', 'district_id' => '57', 'name' => 'Bagherpara ', 'bn_name' => 'বাঘের পাড়া ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '286', 'district_id' => '57', 'name' => 'Jessore Sadar ', 'bn_name' => 'যশোর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '287', 'district_id' => '57', 'name' => 'Chaugachha ', 'bn_name' => 'চৌগাছা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '288', 'district_id' => '57', 'name' => 'Manirampur ', 'bn_name' => 'মনিরামপুর ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '289', 'district_id' => '57', 'name' => 'Jhikargachha ', 'bn_name' => 'ঝিকরগাছা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '290', 'district_id' => '57', 'name' => 'Sharsha ', 'bn_name' => 'সারশা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '291', 'district_id' => '58', 'name' => 'Jhenaidah Sadar ', 'bn_name' => 'ঝিনাইদহ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '292', 'district_id' => '58', 'name' => 'Maheshpur ', 'bn_name' => 'মহেশপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '293', 'district_id' => '58', 'name' => 'Kaliganj ', 'bn_name' => 'কালীগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '294', 'district_id' => '58', 'name' => 'Kotchandpur ', 'bn_name' => 'কোট চাঁদপুর ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '295', 'district_id' => '58', 'name' => 'Shailkupa ', 'bn_name' => 'শৈলকুপা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '296', 'district_id' => '58', 'name' => 'Harinakunda ', 'bn_name' => 'হাড়িনাকুন্দা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '297', 'district_id' => '59', 'name' => 'Terokhada ', 'bn_name' => 'তেরোখাদা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '298', 'district_id' => '59', 'name' => 'Batiaghata ', 'bn_name' => 'বাটিয়াঘাটা ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '299', 'district_id' => '59', 'name' => 'Dacope ', 'bn_name' => 'ডাকপে', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '300', 'district_id' => '59', 'name' => 'Dumuria ', 'bn_name' => 'ডুমুরিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '301', 'district_id' => '59', 'name' => 'Dighalia ', 'bn_name' => 'দিঘলিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '302', 'district_id' => '59', 'name' => 'Koyra ', 'bn_name' => 'কয়ড়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '303', 'district_id' => '59', 'name' => 'Paikgachha ', 'bn_name' => 'পাইকগাছা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '304', 'district_id' => '59', 'name' => 'Phultala ', 'bn_name' => 'ফুলতলা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '305', 'district_id' => '59', 'name' => 'Rupsa ', 'bn_name' => 'রূপসা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '306', 'district_id' => '60', 'name' => 'Kushtia Sadar', 'bn_name' => 'কুষ্টিয়া সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '307', 'district_id' => '60', 'name' => 'Kumarkhali', 'bn_name' => 'কুমারখালি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '308', 'district_id' => '60', 'name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '309', 'district_id' => '60', 'name' => 'Mirpur', 'bn_name' => 'মিরপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '310', 'district_id' => '60', 'name' => 'Bheramara', 'bn_name' => 'ভেরামারা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '311', 'district_id' => '60', 'name' => 'Khoksa', 'bn_name' => 'খোকসা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '312', 'district_id' => '61', 'name' => 'Magura Sadar ', 'bn_name' => 'মাগুরা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '313', 'district_id' => '61', 'name' => 'Mohammadpur ', 'bn_name' => 'মোহাম্মাদপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '314', 'district_id' => '61', 'name' => 'Shalikha ', 'bn_name' => 'শালিখা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '315', 'district_id' => '61', 'name' => 'Sreepur ', 'bn_name' => 'শ্রীপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '316', 'district_id' => '62', 'name' => 'angni ', 'bn_name' => 'আংনি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '317', 'district_id' => '62', 'name' => 'Mujib Nagar ', 'bn_name' => 'মুজিব নগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '318', 'district_id' => '62', 'name' => 'Meherpur-S ', 'bn_name' => 'মেহেরপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '319', 'district_id' => '63', 'name' => 'Narail-S Upazilla', 'bn_name' => 'নড়াইল সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '320', 'district_id' => '63', 'name' => 'Lohagara Upazilla', 'bn_name' => 'লোহাগাড়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '321', 'district_id' => '63', 'name' => 'Kalia Upazilla', 'bn_name' => 'কালিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '322', 'district_id' => '64', 'name' => 'Satkhira Sadar ', 'bn_name' => 'সাতক্ষীরা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '323', 'district_id' => '64', 'name' => 'Assasuni ', 'bn_name' => 'আসসাশুনি ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '324', 'district_id' => '64', 'name' => 'Debhata ', 'bn_name' => 'দেভাটা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '325', 'district_id' => '64', 'name' => 'Tala ', 'bn_name' => 'তালা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '326', 'district_id' => '64', 'name' => 'Kalaroa ', 'bn_name' => 'কলরোয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '327', 'district_id' => '64', 'name' => 'Kaliganj ', 'bn_name' => 'কালীগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '328', 'district_id' => '64', 'name' => 'Shyamnagar ', 'bn_name' => 'শ্যামনগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '329', 'district_id' => '18', 'name' => 'Adamdighi', 'bn_name' => 'আদমদিঘী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '330', 'district_id' => '18', 'name' => 'Bogra Sadar', 'bn_name' => 'বগুড়া সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '331', 'district_id' => '18', 'name' => 'Sherpur', 'bn_name' => 'শেরপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '332', 'district_id' => '18', 'name' => 'Dhunat', 'bn_name' => 'ধুনট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '333', 'district_id' => '18', 'name' => 'Dhupchanchia', 'bn_name' => 'দুপচাচিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '334', 'district_id' => '18', 'name' => 'Gabtali', 'bn_name' => 'গাবতলি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '335', 'district_id' => '18', 'name' => 'Kahaloo', 'bn_name' => 'কাহালু', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '336', 'district_id' => '18', 'name' => 'Nandigram', 'bn_name' => 'নন্দিগ্রাম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '337', 'district_id' => '18', 'name' => 'Sahajanpur', 'bn_name' => 'শাহজাহানপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '338', 'district_id' => '18', 'name' => 'Sariakandi', 'bn_name' => 'সারিয়াকান্দি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '339', 'district_id' => '18', 'name' => 'Shibganj', 'bn_name' => 'শিবগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '340', 'district_id' => '18', 'name' => 'Sonatala', 'bn_name' => 'সোনাতলা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '341', 'district_id' => '19', 'name' => 'Joypurhat S', 'bn_name' => 'জয়পুরহাট সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '342', 'district_id' => '19', 'name' => 'Akkelpur', 'bn_name' => 'আক্কেলপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '343', 'district_id' => '19', 'name' => 'Kalai', 'bn_name' => 'কালাই', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '344', 'district_id' => '19', 'name' => 'Khetlal', 'bn_name' => 'খেতলাল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '345', 'district_id' => '19', 'name' => 'Panchbibi', 'bn_name' => 'পাঁচবিবি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '346', 'district_id' => '20', 'name' => 'Naogaon Sadar ', 'bn_name' => 'নওগাঁ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '347', 'district_id' => '20', 'name' => 'Mohadevpur ', 'bn_name' => 'মহাদেবপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '348', 'district_id' => '20', 'name' => 'Manda ', 'bn_name' => 'মান্দা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '349', 'district_id' => '20', 'name' => 'Niamatpur ', 'bn_name' => 'নিয়ামতপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '350', 'district_id' => '20', 'name' => 'Atrai ', 'bn_name' => 'আত্রাই', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '351', 'district_id' => '20', 'name' => 'Raninagar ', 'bn_name' => 'রাণীনগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '352', 'district_id' => '20', 'name' => 'Patnitala ', 'bn_name' => 'পত্নীতলা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '353', 'district_id' => '20', 'name' => 'Dhamoirhat ', 'bn_name' => 'ধামইরহাট ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '354', 'district_id' => '20', 'name' => 'Sapahar ', 'bn_name' => 'সাপাহার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '355', 'district_id' => '20', 'name' => 'Porsha ', 'bn_name' => 'পোরশা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '356', 'district_id' => '20', 'name' => 'Badalgachhi ', 'bn_name' => 'বদলগাছি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '357', 'district_id' => '21', 'name' => 'Natore Sadar ', 'bn_name' => 'নাটোর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '358', 'district_id' => '21', 'name' => 'Baraigram ', 'bn_name' => 'বড়াইগ্রাম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '359', 'district_id' => '21', 'name' => 'Bagatipara ', 'bn_name' => 'বাগাতিপাড়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '360', 'district_id' => '21', 'name' => 'Lalpur ', 'bn_name' => 'লালপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '361', 'district_id' => '21', 'name' => 'Natore Sadar ', 'bn_name' => 'নাটোর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '362', 'district_id' => '21', 'name' => 'Baraigram ', 'bn_name' => 'বড়াই গ্রাম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '363', 'district_id' => '22', 'name' => 'Bholahat ', 'bn_name' => 'ভোলাহাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '364', 'district_id' => '22', 'name' => 'Gomastapur ', 'bn_name' => 'গোমস্তাপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '365', 'district_id' => '22', 'name' => 'Nachole ', 'bn_name' => 'নাচোল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '366', 'district_id' => '22', 'name' => 'Nawabganj Sadar ', 'bn_name' => 'নবাবগঞ্জ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '367', 'district_id' => '22', 'name' => 'Shibganj ', 'bn_name' => 'শিবগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '368', 'district_id' => '23', 'name' => 'Atgharia ', 'bn_name' => 'আটঘরিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '369', 'district_id' => '23', 'name' => 'Bera ', 'bn_name' => 'বেড়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '370', 'district_id' => '23', 'name' => 'Bhangura ', 'bn_name' => 'ভাঙ্গুরা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '371', 'district_id' => '23', 'name' => 'Chatmohar ', 'bn_name' => 'চাটমোহর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '372', 'district_id' => '23', 'name' => 'Faridpur ', 'bn_name' => 'ফরিদপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '373', 'district_id' => '23', 'name' => 'Ishwardi ', 'bn_name' => 'ঈশ্বরদী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '374', 'district_id' => '23', 'name' => 'Pabna Sadar ', 'bn_name' => 'পাবনা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '375', 'district_id' => '23', 'name' => 'Santhia ', 'bn_name' => 'সাথিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '376', 'district_id' => '23', 'name' => 'Sujanagar ', 'bn_name' => 'সুজানগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '377', 'district_id' => '24', 'name' => 'Bagha', 'bn_name' => 'বাঘা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '378', 'district_id' => '24', 'name' => 'Bagmara', 'bn_name' => 'বাগমারা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '379', 'district_id' => '24', 'name' => 'Charghat', 'bn_name' => 'চারঘাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '380', 'district_id' => '24', 'name' => 'Durgapur', 'bn_name' => 'দুর্গাপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '381', 'district_id' => '24', 'name' => 'Godagari', 'bn_name' => 'গোদাগারি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '382', 'district_id' => '24', 'name' => 'Mohanpur', 'bn_name' => 'মোহনপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '383', 'district_id' => '24', 'name' => 'Paba', 'bn_name' => 'পবা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '384', 'district_id' => '24', 'name' => 'Puthia', 'bn_name' => 'পুঠিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '385', 'district_id' => '24', 'name' => 'Tanore', 'bn_name' => 'তানোর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '386', 'district_id' => '25', 'name' => 'Sirajganj Sadar ', 'bn_name' => 'সিরাজগঞ্জ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '387', 'district_id' => '25', 'name' => 'Belkuchi ', 'bn_name' => 'বেলকুচি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '388', 'district_id' => '25', 'name' => 'Chauhali ', 'bn_name' => 'চৌহালি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '389', 'district_id' => '25', 'name' => 'Kamarkhanda ', 'bn_name' => 'কামারখান্দা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '390', 'district_id' => '25', 'name' => 'Kazipur ', 'bn_name' => 'কাজীপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '391', 'district_id' => '25', 'name' => 'Raiganj ', 'bn_name' => 'রায়গঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '392', 'district_id' => '25', 'name' => 'Shahjadpur ', 'bn_name' => 'শাহজাদপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '393', 'district_id' => '25', 'name' => 'Tarash ', 'bn_name' => 'তারাশ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '394', 'district_id' => '25', 'name' => 'Ullahpara ', 'bn_name' => 'উল্লাপাড়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '395', 'district_id' => '26', 'name' => 'Birampur ', 'bn_name' => 'বিরামপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '396', 'district_id' => '26', 'name' => 'Birganj', 'bn_name' => 'বীরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '397', 'district_id' => '26', 'name' => 'Biral ', 'bn_name' => 'বিড়াল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '398', 'district_id' => '26', 'name' => 'Bochaganj ', 'bn_name' => 'বোচাগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '399', 'district_id' => '26', 'name' => 'Chirirbandar ', 'bn_name' => 'চিরিরবন্দর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '400', 'district_id' => '26', 'name' => 'Phulbari ', 'bn_name' => 'ফুলবাড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '401', 'district_id' => '26', 'name' => 'Ghoraghat ', 'bn_name' => 'ঘোড়াঘাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '402', 'district_id' => '26', 'name' => 'Hakimpur ', 'bn_name' => 'হাকিমপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '403', 'district_id' => '26', 'name' => 'Kaharole ', 'bn_name' => 'কাহারোল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '404', 'district_id' => '26', 'name' => 'Khansama ', 'bn_name' => 'খানসামা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '405', 'district_id' => '26', 'name' => 'Dinajpur Sadar ', 'bn_name' => 'দিনাজপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '406', 'district_id' => '26', 'name' => 'Nawabganj', 'bn_name' => 'নবাবগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '407', 'district_id' => '26', 'name' => 'Parbatipur ', 'bn_name' => 'পার্বতীপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '408', 'district_id' => '27', 'name' => 'Fulchhari', 'bn_name' => 'ফুলছড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '409', 'district_id' => '27', 'name' => 'Gaibandha sadar', 'bn_name' => 'গাইবান্ধা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '410', 'district_id' => '27', 'name' => 'Gobindaganj', 'bn_name' => 'গোবিন্দগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '411', 'district_id' => '27', 'name' => 'Palashbari', 'bn_name' => 'পলাশবাড়ী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '412', 'district_id' => '27', 'name' => 'Sadullapur', 'bn_name' => 'সাদুল্যাপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '413', 'district_id' => '27', 'name' => 'Saghata', 'bn_name' => 'সাঘাটা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '414', 'district_id' => '27', 'name' => 'Sundarganj', 'bn_name' => 'সুন্দরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '415', 'district_id' => '28', 'name' => 'Kurigram Sadar', 'bn_name' => 'কুড়িগ্রাম সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '416', 'district_id' => '28', 'name' => 'Nageshwari', 'bn_name' => 'নাগেশ্বরী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '417', 'district_id' => '28', 'name' => 'Bhurungamari', 'bn_name' => 'ভুরুঙ্গামারি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '418', 'district_id' => '28', 'name' => 'Phulbari', 'bn_name' => 'ফুলবাড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '419', 'district_id' => '28', 'name' => 'Rajarhat', 'bn_name' => 'রাজারহাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '420', 'district_id' => '28', 'name' => 'Ulipur', 'bn_name' => 'উলিপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '421', 'district_id' => '28', 'name' => 'Chilmari', 'bn_name' => 'চিলমারি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '422', 'district_id' => '28', 'name' => 'Rowmari', 'bn_name' => 'রউমারি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '423', 'district_id' => '28', 'name' => 'Char Rajibpur', 'bn_name' => 'চর রাজিবপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '424', 'district_id' => '29', 'name' => 'Lalmanirhat Sadar', 'bn_name' => 'লালমনিরহাট সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '425', 'district_id' => '29', 'name' => 'Aditmari', 'bn_name' => 'আদিতমারি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '426', 'district_id' => '29', 'name' => 'Kaliganj', 'bn_name' => 'কালীগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '427', 'district_id' => '29', 'name' => 'Hatibandha', 'bn_name' => 'হাতিবান্ধা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '428', 'district_id' => '29', 'name' => 'Patgram', 'bn_name' => 'পাটগ্রাম', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '429', 'district_id' => '30', 'name' => 'Nilphamari Sadar', 'bn_name' => 'নীলফামারী সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '430', 'district_id' => '30', 'name' => 'Saidpur', 'bn_name' => 'সৈয়দপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '431', 'district_id' => '30', 'name' => 'Jaldhaka', 'bn_name' => 'জলঢাকা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '432', 'district_id' => '30', 'name' => 'Kishoreganj', 'bn_name' => 'কিশোরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '433', 'district_id' => '30', 'name' => 'Domar', 'bn_name' => 'ডোমার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '434', 'district_id' => '30', 'name' => 'Dimla', 'bn_name' => 'ডিমলা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '435', 'district_id' => '31', 'name' => 'Panchagarh Sadar', 'bn_name' => 'পঞ্চগড় সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '436', 'district_id' => '31', 'name' => 'Debiganj', 'bn_name' => 'দেবীগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '437', 'district_id' => '31', 'name' => 'Boda', 'bn_name' => 'বোদা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '438', 'district_id' => '31', 'name' => 'Atwari', 'bn_name' => 'আটোয়ারি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '439', 'district_id' => '31', 'name' => 'Tetulia', 'bn_name' => 'তেতুলিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '440', 'district_id' => '32', 'name' => 'Badarganj', 'bn_name' => 'বদরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '441', 'district_id' => '32', 'name' => 'Mithapukur', 'bn_name' => 'মিঠাপুকুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '442', 'district_id' => '32', 'name' => 'Gangachara', 'bn_name' => 'গঙ্গাচরা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '443', 'district_id' => '32', 'name' => 'Kaunia', 'bn_name' => 'কাউনিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '444', 'district_id' => '32', 'name' => 'Rangpur Sadar', 'bn_name' => 'রংপুর সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '445', 'district_id' => '32', 'name' => 'Pirgachha', 'bn_name' => 'পীরগাছা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '446', 'district_id' => '32', 'name' => 'Pirganj', 'bn_name' => 'পীরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '447', 'district_id' => '32', 'name' => 'Taraganj', 'bn_name' => 'তারাগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '448', 'district_id' => '33', 'name' => 'Thakurgaon Sadar ', 'bn_name' => 'ঠাকুরগাঁও সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '449', 'district_id' => '33', 'name' => 'Pirganj ', 'bn_name' => 'পীরগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '450', 'district_id' => '33', 'name' => 'Baliadangi ', 'bn_name' => 'বালিয়াডাঙ্গি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '451', 'district_id' => '33', 'name' => 'Haripur ', 'bn_name' => 'হরিপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '452', 'district_id' => '33', 'name' => 'Ranisankail ', 'bn_name' => 'রাণীসংকইল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '453', 'district_id' => '51', 'name' => 'Ajmiriganj', 'bn_name' => 'আজমিরিগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '454', 'district_id' => '51', 'name' => 'Baniachang', 'bn_name' => 'বানিয়াচং', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '455', 'district_id' => '51', 'name' => 'Bahubal', 'bn_name' => 'বাহুবল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '456', 'district_id' => '51', 'name' => 'Chunarughat', 'bn_name' => 'চুনারুঘাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '457', 'district_id' => '51', 'name' => 'Habiganj Sadar', 'bn_name' => 'হবিগঞ্জ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '458', 'district_id' => '51', 'name' => 'Lakhai', 'bn_name' => 'লাক্ষাই', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '459', 'district_id' => '51', 'name' => 'Madhabpur', 'bn_name' => 'মাধবপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '460', 'district_id' => '51', 'name' => 'Nabiganj', 'bn_name' => 'নবীগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '461', 'district_id' => '51', 'name' => 'Shaistagonj ', 'bn_name' => 'শায়েস্তাগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '462', 'district_id' => '52', 'name' => 'Moulvibazar Sadar', 'bn_name' => 'মৌলভীবাজার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '463', 'district_id' => '52', 'name' => 'Barlekha', 'bn_name' => 'বড়লেখা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '464', 'district_id' => '52', 'name' => 'Juri', 'bn_name' => 'জুড়ি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '465', 'district_id' => '52', 'name' => 'Kamalganj', 'bn_name' => 'কামালগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '466', 'district_id' => '52', 'name' => 'Kulaura', 'bn_name' => 'কুলাউরা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '467', 'district_id' => '52', 'name' => 'Rajnagar', 'bn_name' => 'রাজনগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '468', 'district_id' => '52', 'name' => 'Sreemangal', 'bn_name' => 'শ্রীমঙ্গল', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '469', 'district_id' => '53', 'name' => 'Bishwamvarpur', 'bn_name' => 'বিসশম্ভারপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '470', 'district_id' => '53', 'name' => 'Chhatak', 'bn_name' => 'ছাতক', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '471', 'district_id' => '53', 'name' => 'Derai', 'bn_name' => 'দেড়াই', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '472', 'district_id' => '53', 'name' => 'Dharampasha', 'bn_name' => 'ধরমপাশা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '473', 'district_id' => '53', 'name' => 'Dowarabazar', 'bn_name' => 'দোয়ারাবাজার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '474', 'district_id' => '53', 'name' => 'Jagannathpur', 'bn_name' => 'জগন্নাথপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '475', 'district_id' => '53', 'name' => 'Jamalganj', 'bn_name' => 'জামালগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '476', 'district_id' => '53', 'name' => 'Sulla', 'bn_name' => 'সুল্লা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '477', 'district_id' => '53', 'name' => 'Sunamganj Sadar', 'bn_name' => 'সুনামগঞ্জ সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '478', 'district_id' => '53', 'name' => 'Shanthiganj', 'bn_name' => 'শান্তিগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '479', 'district_id' => '53', 'name' => 'Tahirpur', 'bn_name' => 'তাহিরপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '480', 'district_id' => '54', 'name' => 'Sylhet Sadar', 'bn_name' => 'সিলেট সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '481', 'district_id' => '54', 'name' => 'Beanibazar', 'bn_name' => 'বেয়ানিবাজার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '482', 'district_id' => '54', 'name' => 'Bishwanath', 'bn_name' => 'বিশ্বনাথ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '483', 'district_id' => '54', 'name' => 'Dakshin Surma ', 'bn_name' => 'দক্ষিণ সুরমা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '484', 'district_id' => '54', 'name' => 'Balaganj', 'bn_name' => 'বালাগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '485', 'district_id' => '54', 'name' => 'Companiganj', 'bn_name' => 'কোম্পানিগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '486', 'district_id' => '54', 'name' => 'Fenchuganj', 'bn_name' => 'ফেঞ্চুগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '487', 'district_id' => '54', 'name' => 'Golapganj', 'bn_name' => 'গোলাপগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '488', 'district_id' => '54', 'name' => 'Gowainghat', 'bn_name' => 'গোয়াইনঘাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '489', 'district_id' => '54', 'name' => 'Jaintiapur', 'bn_name' => 'জয়ন্তপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '490', 'district_id' => '54', 'name' => 'Kanaighat', 'bn_name' => 'কানাইঘাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '491', 'district_id' => '54', 'name' => 'Zakiganj', 'bn_name' => 'জাকিগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '492', 'district_id' => '54', 'name' => 'Nobigonj', 'bn_name' => 'নবীগঞ্জ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '493', 'district_id' => '1', 'name' => 'Adabor', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '494', 'district_id' => '1', 'name' => 'Airport', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '495', 'district_id' => '1', 'name' => 'Badda', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '496', 'district_id' => '1', 'name' => 'Banani', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '497', 'district_id' => '1', 'name' => 'Bangshal', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '498', 'district_id' => '1', 'name' => 'Bhashantek', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '499', 'district_id' => '1', 'name' => 'Cantonment', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '500', 'district_id' => '1', 'name' => 'Chackbazar', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '501', 'district_id' => '1', 'name' => 'Darussalam', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '502', 'district_id' => '1', 'name' => 'Daskhinkhan', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '503', 'district_id' => '1', 'name' => 'Demra', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '504', 'district_id' => '1', 'name' => 'Dhamrai', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '505', 'district_id' => '1', 'name' => 'Dhanmondi', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '506', 'district_id' => '1', 'name' => 'Dohar', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '507', 'district_id' => '1', 'name' => 'Gandaria', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '508', 'district_id' => '1', 'name' => 'Gulshan', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '509', 'district_id' => '1', 'name' => 'Hazaribag', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '510', 'district_id' => '1', 'name' => 'Jatrabari', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '511', 'district_id' => '1', 'name' => 'Kafrul', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '512', 'district_id' => '1', 'name' => 'Kalabagan', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '513', 'district_id' => '1', 'name' => 'Kamrangirchar', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '514', 'district_id' => '1', 'name' => 'Keraniganj', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '515', 'district_id' => '1', 'name' => 'Khilgaon', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '516', 'district_id' => '1', 'name' => 'Khilkhet', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '517', 'district_id' => '1', 'name' => 'Kotwali', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '518', 'district_id' => '1', 'name' => 'Lalbag', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '519', 'district_id' => '1', 'name' => 'Mirpur Model', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '520', 'district_id' => '1', 'name' => 'Mohammadpur', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '521', 'district_id' => '1', 'name' => 'Motijheel', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '522', 'district_id' => '1', 'name' => 'Mugda', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '523', 'district_id' => '1', 'name' => 'Nawabganj', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '524', 'district_id' => '1', 'name' => 'New Market', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '525', 'district_id' => '1', 'name' => 'Pallabi', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '526', 'district_id' => '1', 'name' => 'Paltan', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '527', 'district_id' => '1', 'name' => 'Ramna', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '528', 'district_id' => '1', 'name' => 'Rampura', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '529', 'district_id' => '1', 'name' => 'Rupnagar', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '530', 'district_id' => '1', 'name' => 'Sabujbag', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '531', 'district_id' => '1', 'name' => 'Savar', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '532', 'district_id' => '1', 'name' => 'Shah Ali', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '533', 'district_id' => '1', 'name' => 'Shahbag', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '534', 'district_id' => '1', 'name' => 'Shahjahanpur', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '535', 'district_id' => '1', 'name' => 'Sherebanglanagar', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '536', 'district_id' => '1', 'name' => 'Shyampur', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '537', 'district_id' => '1', 'name' => 'Sutrapur', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '538', 'district_id' => '1', 'name' => 'Tejgaon', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '539', 'district_id' => '1', 'name' => "Tejgaon I\/A", 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '540', 'district_id' => '1', 'name' => 'Turag', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '541', 'district_id' => '1', 'name' => 'Uttara', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '542', 'district_id' => '1', 'name' => 'Uttara West', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '543', 'district_id' => '1', 'name' => 'Uttarkhan', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '544', 'district_id' => '1', 'name' => 'Vatara', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '545', 'district_id' => '1', 'name' => 'Wari', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '546', 'district_id' => '1', 'name' => 'Others', 'bn_name' => null, 'created_at' => now(), 'updated_at' => now()],
            ['id' => '547', 'district_id' => '35', 'name' => 'Airport', 'bn_name' => 'এয়ারপোর্ট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '548', 'district_id' => '35', 'name' => 'Kawnia', 'bn_name' => 'কাউনিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '549', 'district_id' => '35', 'name' => 'Bondor', 'bn_name' => 'বন্দর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '550', 'district_id' => '35', 'name' => 'Others', 'bn_name' => 'অন্যান্য', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '551', 'district_id' => '24', 'name' => 'Boalia', 'bn_name' => 'বোয়ালিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '552', 'district_id' => '24', 'name' => 'Motihar', 'bn_name' => 'মতিহার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '553', 'district_id' => '24', 'name' => 'Shahmokhdum', 'bn_name' => 'শাহ্ মকখদুম ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '554', 'district_id' => '24', 'name' => 'Rajpara', 'bn_name' => 'রাজপারা ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '555', 'district_id' => '24', 'name' => 'Others', 'bn_name' => 'অন্যান্য', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '556', 'district_id' => '43', 'name' => 'Akborsha', 'bn_name' => 'Akborsha', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '557', 'district_id' => '43', 'name' => 'Baijid bostami', 'bn_name' => 'বাইজিদ বোস্তামী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '558', 'district_id' => '43', 'name' => 'Bakolia', 'bn_name' => 'বাকোলিয়া', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '559', 'district_id' => '43', 'name' => 'Bandar', 'bn_name' => 'বন্দর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '560', 'district_id' => '43', 'name' => 'Chandgaon', 'bn_name' => 'চাঁদগাও', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '561', 'district_id' => '43', 'name' => 'Chokbazar', 'bn_name' => 'চকবাজার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '562', 'district_id' => '43', 'name' => 'Doublemooring', 'bn_name' => 'ডাবল মুরিং', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '563', 'district_id' => '43', 'name' => 'EPZ', 'bn_name' => 'ইপিজেড', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '564', 'district_id' => '43', 'name' => 'Hali Shohor', 'bn_name' => 'হলী শহর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '565', 'district_id' => '43', 'name' => 'Kornafuli', 'bn_name' => 'কর্ণফুলি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '566', 'district_id' => '43', 'name' => 'Kotwali', 'bn_name' => 'কোতোয়ালী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '567', 'district_id' => '43', 'name' => 'Kulshi', 'bn_name' => 'কুলশি', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '568', 'district_id' => '43', 'name' => 'Pahartali', 'bn_name' => 'পাহাড়তলী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '569', 'district_id' => '43', 'name' => 'Panchlaish', 'bn_name' => 'পাঁচলাইশ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '570', 'district_id' => '43', 'name' => 'Potenga', 'bn_name' => 'পতেঙ্গা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '571', 'district_id' => '43', 'name' => 'Shodhorgat', 'bn_name' => 'সদরঘাট', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '572', 'district_id' => '43', 'name' => 'Others', 'bn_name' => 'অন্যান্য', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '573', 'district_id' => '44', 'name' => 'Others', 'bn_name' => 'অন্যান্য', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '574', 'district_id' => '59', 'name' => 'Aranghata', 'bn_name' => 'আড়াংঘাটা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '575', 'district_id' => '59', 'name' => 'Daulatpur', 'bn_name' => 'দৌলতপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '576', 'district_id' => '59', 'name' => 'Harintana', 'bn_name' => 'হারিন্তানা ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '577', 'district_id' => '59', 'name' => 'Horintana', 'bn_name' => 'হরিণতানা ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '578', 'district_id' => '59', 'name' => 'Khalishpur', 'bn_name' => 'খালিশপুর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '579', 'district_id' => '59', 'name' => 'Khanjahan Ali', 'bn_name' => 'খানজাহান আলী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '580', 'district_id' => '59', 'name' => 'Khulna Sadar', 'bn_name' => 'খুলনা সদর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '581', 'district_id' => '59', 'name' => 'Labanchora', 'bn_name' => 'লাবানছোরা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '582', 'district_id' => '59', 'name' => 'Sonadanga', 'bn_name' => 'সোনাডাঙ্গা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '583', 'district_id' => '59', 'name' => 'Others', 'bn_name' => 'অন্যান্য', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '584', 'district_id' => '2', 'name' => 'Others', 'bn_name' => 'অন্যান্য', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '585', 'district_id' => '4', 'name' => 'Others', 'bn_name' => 'অন্যান্য', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '586', 'district_id' => '5', 'name' => 'Others', 'bn_name' => 'অন্যান্য', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '587', 'district_id' => '54', 'name' => 'Airport', 'bn_name' => 'বিমানবন্দর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '588', 'district_id' => '54', 'name' => 'Hazrat Shah Paran', 'bn_name' => 'হযরত শাহ পরাণ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '589', 'district_id' => '54', 'name' => 'Jalalabad', 'bn_name' => 'জালালাবাদ', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '590', 'district_id' => '54', 'name' => 'Kowtali', 'bn_name' => 'কোতোয়ালী', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '591', 'district_id' => '54', 'name' => 'Moglabazar', 'bn_name' => 'মোগলাবাজার', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '592', 'district_id' => '54', 'name' => 'Osmani Nagar', 'bn_name' => 'ওসমানী নগর', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '593', 'district_id' => '54', 'name' => 'South Surma', 'bn_name' => 'দক্ষিণ সুরমা', 'created_at' => now(), 'updated_at' => now()],
            ['id' => '594', 'district_id' => '54', 'name' => 'Others', 'bn_name' => 'অন্যান্য', 'created_at' => now(), 'updated_at' => now()],
            ];

        Upazila::insertOrIgnore($UpazilaList);
    }
}
